import { WebProvider } from "@/utilities/WebContext";
import "./globals.css";
import localFont from "next/font/local";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Frontend Mentor | Multi-step form",
  description: "Generated by create next app",
};

const UB = localFont({
  src: "../assets/fonts/Ubuntu-Bold.ttf",
  variable: "--UB",
});
const UM = localFont({
  src: "../assets/fonts/Ubuntu-Medium.ttf",
  variable: "--UM",
});
const UR = localFont({
  src: "../assets/fonts/Ubuntu-Regular.ttf",
  variable: "--UR",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${UB.variable} ${UM.variable} ${UR.variable}`}>
      <body>
        <WebProvider>
          <>{children}</>
        </WebProvider>
        <Analytics />
      </body>
    </html>
  );
}
